dist: bionic
language: python
python:
    - "3.8"

before_install:
    - pip install pipenv
install:
    - pipenv install --dev
    - pip install black==18.9b0
    - sudo apt-get install rabbitmq-server

stages:
    - Statis Analisis
    - Test

black:
	stage: Static Analysis
	script:
	- pipenv run black --check

flake8:
	stage: Static Analysis
	script:
	- pipenv run flake8

pylint:
	stage: Static Analysis
	allow_failure: true
	script:
		- pipenv run pylint

unit_test:
	stage: Test
	script:
	- pipenv run pytest -vv --color=yes --cov=omega --cov-report term-missing:skip-covered
